name: app_multivisio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
    
  http: 0.13.6
  web_socket_channel: ^3.0.1
  video_player: ^2.4.5
  # http: ^0.13.5
  # web_socket_channel: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

